model: SM-S918B
soc: sm8550
fstab: fstab.qcom
super_type: dynamic
family: dmqxxx
variant: dm3q
output_name: dm3q
super_group_name: qti_dynamic_partitions
super_partition_size: 12107358208
super_group_size: 12103163904
super_metadata_slots: 2

partitions:
  - system
  - vendor
  - product
  - odm

security:
  disable_vaultkeeper: true
  disable_proca: qsee

features:
  call_recording: true
  battery_health_menu: true
  debloat_bixby: true
  debloat_samsung_account: false
